# Generated by Django 2.2 on 2020-12-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laughing', '0002_auto_20201201_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='postq',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
