# Generated by Django 2.2 on 2020-12-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laughing', '0003_postq_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postq',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
