# Generated by Django 2.2 on 2020-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laughing', '0004_auto_20201201_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
