# Generated by Django 2.2 on 2020-12-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laughing', '0006_auto_20201201_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='postq',
            name='category',
            field=models.CharField(choices=[('A', 'Agriculture'), ('B', 'Banking'), ('E', 'Electrical'), ('M', 'Mechanic')], default='A', max_length=2),
            preserve_default=False,
        ),
    ]
